name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.11.1]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i -g --unsafe-perm=true ganache-cli npm-auto-version
    - run: npm i
    - run: ./scripts/start_ganache.sh
    - run: ./scripts/truffle_test.sh
    - run: npm i -g ethereum-contract-sexy-manager
    - run: sexydynamite -v
    - run: sexydynamite init
    - run: sexydynamite create -c Sample1
      env:
        CI: true
